export type CoachVibe = 'warm' | 'direct' | 'intense';
export type CoachGender = 'F' | 'M';
export type CoachBodyType = 'Athletic' | 'Strong & powerful';

export interface Coach {
  id: number;
  name: string;
  gender: CoachGender;
  age: number;
  vibe: CoachVibe;
  bodyType: CoachBodyType;
  bio: string;
  tier: 'free' | 'premium';
}

export const FREE_COACHES: Coach[] = [
  // WARM — 7
  {
    id: 1,
    name: 'Mara',
    gender: 'F',
    age: 29,
    vibe: 'warm',
    bodyType: 'Athletic',
    tier: 'free',
    bio: "Former endurance coach turned everyday athlete. Believes fitness should feel sustainable, not punishing — showing up on hard days matters more than PRs.",
  },
  {
    id: 2,
    name: 'Sofia',
    gender: 'F',
    age: 31,
    vibe: 'warm',
    bodyType: 'Athletic',
    tier: 'free',
    bio: "Certified personal trainer and former dance instructor. Believes movement should be something you look forward to, not dread.",
  },
  {
    id: 3,
    name: 'Marcus',
    gender: 'M',
    age: 37,
    vibe: 'warm',
    bodyType: 'Strong & powerful',
    tier: 'free',
    bio: "Former high school track coach. Leads with encouragement, knows exactly when to push harder and when to back off.",
  },
  {
    id: 4,
    name: 'Ben',
    gender: 'M',
    age: 34,
    vibe: 'warm',
    bodyType: 'Strong & powerful',
    tier: 'free',
    bio: "Former collegiate swimmer. Consistency beats intensity every time — and he'll be there to prove it with you.",
  },
  {
    id: 5,
    name: 'Chloe',
    gender: 'F',
    age: 32,
    vibe: 'warm',
    bodyType: 'Athletic',
    tier: 'free',
    bio: "Group fitness instructor turned one-on-one coach. Most fitness struggles aren't about willpower — they're about finding the right approach.",
  },
  {
    id: 6,
    name: 'Hannah',
    gender: 'F',
    age: 36,
    vibe: 'warm',
    bodyType: 'Athletic',
    tier: 'free',
    bio: "Personal trainer and mother of two. Found passion after her own postpartum journey. Meets every client exactly where they are.",
  },
  {
    id: 7,
    name: 'David',
    gender: 'M',
    age: 47,
    vibe: 'warm',
    bodyType: 'Athletic',
    tier: 'free',
    bio: "Former corporate executive who overhauled his health at 40. Coaches with the perspective of someone who's been too busy, too tired, too overwhelmed.",
  },
  // DIRECT — 4
  {
    id: 8,
    name: 'Kai',
    gender: 'M',
    age: 31,
    vibe: 'direct',
    bodyType: 'Athletic',
    tier: 'free',
    bio: "Nordic athletic training background. Structure, consistency, zero wasted effort. Respects your time, tells you exactly what to do, trusts you to do it.",
  },
  {
    id: 9,
    name: 'Jordan',
    gender: 'F',
    age: 27,
    vibe: 'direct',
    bodyType: 'Athletic',
    tier: 'free',
    bio: "Former college athlete coach. Doesn't do small talk — she does results.",
  },
  {
    id: 10,
    name: 'Carmen',
    gender: 'F',
    age: 33,
    vibe: 'direct',
    bodyType: 'Athletic',
    tier: 'free',
    bio: "Biomechanics specialist. Approaches fitness like an engineer — precise, methodical, outcome-focused.",
  },
  {
    id: 11,
    name: 'Sam',
    gender: 'M',
    age: 26,
    vibe: 'direct',
    bodyType: 'Athletic',
    tier: 'free',
    bio: "Track and field coach. Gets more done in 30 minutes than most coaches will in an hour.",
  },
  // INTENSE — 3
  {
    id: 12,
    name: 'Reese',
    gender: 'F',
    age: 26,
    vibe: 'intense',
    bodyType: 'Athletic',
    tier: 'free',
    bio: "Former D1 sprinter. Celebrates loud, pushes hard, believes everyone is capable of more than they think.",
  },
  {
    id: 13,
    name: 'Dom',
    gender: 'M',
    age: 34,
    vibe: 'intense',
    bodyType: 'Strong & powerful',
    tier: 'free',
    bio: "Trained semi-professional MMA fighters. Doesn't believe in easy days — believes in earned ones.",
  },
  {
    id: 14,
    name: 'Andre',
    gender: 'M',
    age: 28,
    vibe: 'intense',
    bodyType: 'Strong & powerful',
    tier: 'free',
    bio: "Former competitive rugby player. Raw energy, relentless drive. Demanding, real, impossible to quit on.",
  },
];

export const PREMIUM_COACHES: Coach[] = [
  // WARM — 5
  {
    id: 15,
    name: 'Priya',
    gender: 'F',
    age: 33,
    vibe: 'warm',
    bodyType: 'Athletic',
    tier: 'premium',
    bio: "Trained in yoga and sports psychology. Builds programs around your real life — not an idealized version of it.",
  },
  {
    id: 16,
    name: 'Tyler',
    gender: 'M',
    age: 39,
    vibe: 'warm',
    bodyType: 'Athletic',
    tier: 'premium',
    bio: "Physical therapist turned coach. Understands bodies deeply — how they break, how they heal, how to build smarter.",
  },
  {
    id: 17,
    name: 'Naomi',
    gender: 'F',
    age: 44,
    vibe: 'warm',
    bodyType: 'Strong & powerful',
    tier: 'premium',
    bio: "Former competitive weightlifter, now focused on longevity. Proves the best years of training can come after 40.",
  },
  {
    id: 18,
    name: 'Eli',
    gender: 'M',
    age: 30,
    vibe: 'warm',
    bodyType: 'Athletic',
    tier: 'premium',
    bio: "Ultra-marathon runner with a gentle coaching style. Believes in building the mental game as much as the physical one.",
  },
  {
    id: 19,
    name: 'Grace',
    gender: 'F',
    age: 35,
    vibe: 'warm',
    bodyType: 'Athletic',
    tier: 'premium',
    bio: "Blends strength and mindful movement. Knows that consistency comes from feeling good, not just looking good.",
  },
  // DIRECT — 5
  {
    id: 20,
    name: 'Alex',
    gender: 'M',
    age: 32,
    vibe: 'direct',
    bodyType: 'Athletic',
    tier: 'premium',
    bio: "Former Army Ranger physical training lead. Precise, no-nonsense, and relentlessly practical.",
  },
  {
    id: 21,
    name: 'Zoe',
    gender: 'F',
    age: 29,
    vibe: 'direct',
    bodyType: 'Athletic',
    tier: 'premium',
    bio: "CrossFit coach and regional competitor. Turns complex programming into clear, executable plans.",
  },
  {
    id: 22,
    name: 'Derek',
    gender: 'M',
    age: 41,
    vibe: 'direct',
    bodyType: 'Strong & powerful',
    tier: 'premium',
    bio: "Powerlifting coach with 15 years in strength sports. Every session has a purpose, every lift has a reason.",
  },
  {
    id: 23,
    name: 'Lily',
    gender: 'F',
    age: 36,
    vibe: 'direct',
    bodyType: 'Athletic',
    tier: 'premium',
    bio: "HIIT and metabolic conditioning specialist. Makes every minute count — no filler, no fluff.",
  },
  {
    id: 24,
    name: 'Cole',
    gender: 'M',
    age: 28,
    vibe: 'direct',
    bodyType: 'Athletic',
    tier: 'premium',
    bio: "Sprint and speed coach. Ruthlessly efficient — because your time is the most valuable thing you spend here.",
  },
  // INTENSE — 4
  {
    id: 25,
    name: 'Rox',
    gender: 'F',
    age: 30,
    vibe: 'intense',
    bodyType: 'Strong & powerful',
    tier: 'premium',
    bio: "Former amateur boxer and strength competitor. Brings fire to every session — and expects you to bring yours.",
  },
  {
    id: 26,
    name: 'Titan',
    gender: 'M',
    age: 35,
    vibe: 'intense',
    bodyType: 'Strong & powerful',
    tier: 'premium',
    bio: "Strongman competitor turned coach. Redefines what you think your body can do — then pushes past it.",
  },
  {
    id: 27,
    name: 'Nova',
    gender: 'F',
    age: 27,
    vibe: 'intense',
    bodyType: 'Athletic',
    tier: 'premium',
    bio: "Track and field athlete, Olympic trials qualifier. Her standard is excellence — and she expects nothing less.",
  },
  {
    id: 28,
    name: 'Cruz',
    gender: 'M',
    age: 32,
    vibe: 'intense',
    bodyType: 'Athletic',
    tier: 'premium',
    bio: "Combat sports trainer who's worked with pro MMA fighters. High intensity, high accountability, zero excuses.",
  },
];

export const ALL_COACHES: Coach[] = [...FREE_COACHES, ...PREMIUM_COACHES];

export const CONSTRAINT_CHIPS = [
  'Bad knees',
  'Bad back',
  'No gym access',
  'Home workouts only',
  'Vegetarian',
  'Vegan',
  'Gluten free',
  'Traveling often',
  'Early mornings only',
  'Under 6hrs sleep',
  '30 min max sessions',
] as const;

export type ConstraintChip = (typeof CONSTRAINT_CHIPS)[number];
